---
name: build-chart
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      ARGOCD_PASSWORD:
        required: true
      ARGOCD_SERVER:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: env/prod

    - name: App Sync
      uses: ahmdelemam/svc-ci-bootstrap/actions/argocd-app-sync@main
