---
name: build-chart
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      ARGOCD_PASSWORD:
        required: true
      ARGOCD_SERVER:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: env/prod
    - name: Setup ArgoCD CLI
      shell: bash
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.10.0/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd   
    - name: Create ArgoCD application
      shell: bash
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure --grpc-web
        argocd app create -f application/${{ inputs.service_name }}-argocd-app.yaml || true
    - name: Sync ArgoCD application
      shell: bash
      run: |
        argocd app sync ${{ inputs.service_name }}
